# Лабораторная работа 2
# Встроенные типы обьектов в Python
**Мусаев Артём Азадович** **14.03.2025**

# *Задание 1*


# иерархическая модель типов встроенных объектов Python.


 Встроенные типы объектов делятся на:
 
 1. Числа:
    
     - Целые числа(`int`), неизменяемые
       
     - числа с плавающей точкой(`float`), неизменяемые
      
     - комплексные числа(`complex`), неизменяемые
   
     - Булевый тип(`bool`) - наследуется от `int`, неизменяемые
       

 2. Коллекции:
    
     - Последовательности:
   
       - строки(`str`), неупорядоченные, неизменяемые.
         
       - списки(`list`), упорядоченные, изменяемые.
         
       - кортежи(`tuple`), упорядоченные, неизменяемые.
       
     - Отображения:
   
        - словари(`dict`), неупорядоченные, изменяемые.
      
     - Множества:
   
        - множества(`set`), неупорядоченные, изменяемые.
   
     

Пример литералов для создания обьекта:

- `42` - для `int`

- `3.14` - для `float`

- `1 + 1j` - для `complex`

- `True` , `False` - для `bool`

- `"Hello"` - для `str`

- `[1,2,3]` - для `list`

- `(1,2,3)` - для `tuple`

- `{'a': 1, 'b': 2}` - для `dict`

- `{1, 2, 3}` - для `set`
    

# Задание 2.
# Задание 2.1

# Тема 2. Объект как фундаментальное понятие в Python. Встроенные типы обьектов:

 - ## 2.1 Понятие объекта. Атрибуты. Методы. Встроенные типы объектов

 - ## 2.2 Встроенные типы объектов, представляющих числа
 
 - ## 2.3 Встроенные типы последовательностей: str, list, tuple

 - ## 2.4 Встроенный тип отображения: dict

 - ## 2.5 Встроенный тип множества: set

 - ## 2.6 Встроенный булевый тип

 - ## 2.7 Изменяемые и неизменяемые встроенные типы объектов

 - ## 2.8 Интерфейс объекта: операции и методы

 - ## 2.9 Переменная

 - ## 2.10 Выражение спискового включения

 - ## 2.11 Форматированный вывод строк

 - ## 2.12 Файловый объект


# Задание 2.2

## 2.2 Встроенные типы объектов, представляющих числа

In [1]:
import decimal

a = decimal.Decimal('0.1')
b = decimal.Decimal('0.2')

sum = a + b
multi = a * b
division = a / b

print (a, b)
print(sum, multi, division)



0.1 0.2
0.3 0.02 0.5


In [2]:
from fractions import Fraction


x = Fraction(1, 2)
y = Fraction(2, 3)


sum = x + y
multi = x * y
division = x / y

print(x, y)
print(sum, multi,division)


1/2 2/3
7/6 1/3 3/4


  ## 2.3 Встроенные типы последовательностей: str, list, tuple

In [3]:
S = 'spam'
print(S)
S = S[:1] + 'l' + S[2:]
print(S)  


spam
slam


S[:1]: Нарезка строки, которая выбирает все символы строки S от начала до индекса 1 (не включая символ на индексе 1). В нашем случае, если S = 'spam', то S[:1] вернет 's'.

'l': Конкатенация строки. Мы добавляем новый символ 'l' в строку.

S[2:]: Нарезка строки, которая выбирает все символы строки S, начиная с индекса 2 до конца строки. В нашем случае, если S = 'spam', то S[2:] вернет 'am'.

`Можно ли выполнить эту операцию с применением только индексации и конкатенации?:` 
Нет, нельзя. Строки в Python являются неизменяемыми (immutable), поэтому присваивание по индексу невозможно. Нельзя напрямую изменить отдельный символ строки.
`Присваивание по индексу для строк` также **невозможно**, потому что строки неизменяемы.

Для списка(`list`):

In [4]:
L = ['s', 'p', 'a', 'm']
L[1] = 'l'
print(L)  


['s', 'l', 'a', 'm']


Для кортежа(`tuple`):

In [5]:
T = ('s', 'p', 'a', 'm')
T = T[:1] + ('l',) + T[2:]
print(T)  


('s', 'l', 'a', 'm')


## 2.4 Встроенный тип отображения: dict

In [6]:

privathayainformaziya = {
    "имя": "Иван",
    "отчество": "Дмитриевич",
    "фамилия": "Домаш",
    "возраст": 18,
    "место работы": " BSU",
    "адрес": "Минск, Беларусь",
    "email": "ivan.domash@inbox.ru",
    "телефон": "+375297752329"
}

name = privathayainformaziya["имя"]
age = privathayainformaziya["возраст"]
email = privathayainformaziya["email"]
print(name, age, email)





Иван 18 ivan.domash@inbox.ru


тот же словарь будет более удобен, так как:

 - Легко получать доступ к значениям по ключам.

 - Удобно добавлять и изменять данные.

 - Понятная структура данных.

a tuple менее приятен, т.к. к примеру требуют больше усилий для доступа к значениям по индексу.

## 2.5 Встроенный тип множества: set

In [7]:

sunsset = "sssuunnset"


sunset = set(sunsset)


riseagain = ''.join(sunset)

print(sunsset)
print(riseagain)

sssuunnset
enust


получилось `stenu`, хотя должно было быть `sunet`, видимо, порядок теряетсЯ

## 2.8 Интерфейс объекта: операции и методы
## 2.8.1

In [8]:
s = "hello world"
scount = s.count('o')
sindex = s.index('o')
print(scount, sindex)


2 4


In [9]:
lst = [1, 2, 3, 2, 1]
lcount = lst.count(2)
lindex = lst.index(2)
print(lcount, lindex)


2 1


In [10]:
tpl = (1, 2, 3, 2, 1)
tcount = tpl.count(2)
tindex = tpl.index(2)
print(tcount, tindex)

2 1


## 2.8.2

## Пример выражения с тремя строковыми методами.


In [11]:
s = "sounds great"
result = s.upper().replace("GREAT", "AWFUL").split()
print(result)



['SOUNDS', 'AWFUL']


**Спецификации:**
 - `upper`: Преобразует все буквы строки в верхний регистр.

 - `replace`: Заменяет все вхождения подстроки на  новые.

 - `split`: Разбивает строку на список подстрок по заданному разделителю.

## 2.8.3

In [12]:
lst = [1, 3, 3]
lst.append(4)
print(lst)



[1, 3, 3, 4]


In [13]:
lst = [1, 2, 3]
lst.extend([4, 5, 'g'])
print(lst)

[1, 2, 3, 4, 5, 'g']


In [14]:
lst = [1, 2, 3]
lst.insert(1, 5000)
print(lst)



[1, 5000, 2, 3]


## 2.8.4

In [15]:
lst = ["dlin", "dlinana", "dlina"]
lst.sort(key=len) # по длине
print(lst)


['dlin', 'dlina', 'dlinana']


## 2.8.5

In [16]:
d = {i: "-7" for i in range(100)}
print(d)


{0: '-7', 1: '-7', 2: '-7', 3: '-7', 4: '-7', 5: '-7', 6: '-7', 7: '-7', 8: '-7', 9: '-7', 10: '-7', 11: '-7', 12: '-7', 13: '-7', 14: '-7', 15: '-7', 16: '-7', 17: '-7', 18: '-7', 19: '-7', 20: '-7', 21: '-7', 22: '-7', 23: '-7', 24: '-7', 25: '-7', 26: '-7', 27: '-7', 28: '-7', 29: '-7', 30: '-7', 31: '-7', 32: '-7', 33: '-7', 34: '-7', 35: '-7', 36: '-7', 37: '-7', 38: '-7', 39: '-7', 40: '-7', 41: '-7', 42: '-7', 43: '-7', 44: '-7', 45: '-7', 46: '-7', 47: '-7', 48: '-7', 49: '-7', 50: '-7', 51: '-7', 52: '-7', 53: '-7', 54: '-7', 55: '-7', 56: '-7', 57: '-7', 58: '-7', 59: '-7', 60: '-7', 61: '-7', 62: '-7', 63: '-7', 64: '-7', 65: '-7', 66: '-7', 67: '-7', 68: '-7', 69: '-7', 70: '-7', 71: '-7', 72: '-7', 73: '-7', 74: '-7', 75: '-7', 76: '-7', 77: '-7', 78: '-7', 79: '-7', 80: '-7', 81: '-7', 82: '-7', 83: '-7', 84: '-7', 85: '-7', 86: '-7', 87: '-7', 88: '-7', 89: '-7', 90: '-7', 91: '-7', 92: '-7', 93: '-7', 94: '-7', 95: '-7', 96: '-7', 97: '-7', 98: '-7', 99: '-7'}


## 2.9 Переменная 

In [17]:
a = [1, 2, 3]
a.append(a)
print(a)  

[1, 2, 3, [...]]


In [18]:
slovar = {'od': 'tr'}
slovar['uf'] = slovar
print(slovar)  # Output: {'key': 'value', 'self': {...}}


{'od': 'tr', 'uf': {...}}


In [19]:
obj = [13]
a = b = c = d = obj
print(a, b, c, d)  


[13] [13] [13] [13]


**Приведите три различных способа копирования списка.**

In [20]:
origin = [1, 2, 3]
copy = list(origin)
print(copy)  


[1, 2, 3]


In [21]:
origin = [1, 2, 3]
copy = origin.copy()
print(copy) 

[1, 2, 3]


In [22]:
origin = [1, 2, 3]
copy = origin
print(copy) 

[1, 2, 3]


## 2.10 Выражение спискового включения

In [23]:
nechet = {x for x in range(10) if x % 2 == 1}
print(nechet)

{1, 3, 5, 7, 9}


In [24]:
matrix = [[ i + j for j in range(8)] for i in range(7)]
for row in matrix:
    print(row)

[0, 1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8, 9, 10]
[4, 5, 6, 7, 8, 9, 10, 11]
[5, 6, 7, 8, 9, 10, 11, 12]
[6, 7, 8, 9, 10, 11, 12, 13]


In [25]:
import numpy as np
matrix = np.arange(56).reshape(7, 8)
print(matrix)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


In [26]:
slojnidict = {i: {'a': i ** 2 } for i in range(4)}
print(slojnidict)

{0: {'a': 0}, 1: {'a': 1}, 2: {'a': 4}, 3: {'a': 9}}


## 2.11 Форматированный вывод строк

-

In [27]:
variable = 52
fstring = f'{variable =:3}'
print(fstring)

variable = 52


In [28]:
variable = 52
f1string = 'variable =%3d' % variable
print(f1string)



variable = 52


In [29]:
variable = 52
f2string = 'variable ={:3}'.format(variable)
print(f2string)




variable = 52


In [30]:
expression = 52 * 2
estring = f'{expression=:.0f}'
print(estring)




expression=104


In [31]:

expression = 52 * 2
e1string = 'expression=%.1f' % expression
print(e1string)

expression=104.0


In [32]:

expression = 52 * 2
e2string = 'expression={:.2f}'.format(expression)
print(e2string)

expression=104.00


## 2.12 Файловый объект

In [33]:
file_path = r"C:\Users\user\Desktop\Привет как дела.txt"


file = open(file_path,  encoding='utf-8')
content = file.read()
print("Содержимое файла:")
print(content)
file = open(file_path, 'r', encoding='utf-8')
lines = file.readlines()
print(lines)
file = open(file_path, 'r', encoding='utf-8')
line = file.readline()
print(line)
file = open(file_path, 'a', encoding='utf-8')


file.write("Это новая строка\n")
file.writelines(["еще\n", "и еще\n"])
file.close()
file = open(file_path, 'r', encoding='utf-8')
content = file.read()
print(content)
file.close()






Содержимое файла:
привет
как
дела

Это новая строка
еще
и еще

['привет\n', 'как\n', 'дела\n', '\n', 'Это новая строка\n', 'еще\n', 'и еще\n']
привет

привет
как
дела

Это новая строка
еще
и еще
Это новая строка
еще
и еще



## Задание 2.3


## 1.


Ошибка возникает так как мы выходим за пределы нашей строки `str1` пытаясь вызвать `[10]` элемент строки
`str1 = 'String'` в ней всего 5 элементов начиная с нулевого.

# 2.


In [4]:
[1] + '1'


TypeError: can only concatenate list (not "str") to list

Ошибка возникает так как мы не можем 
использовать последовательности различных типов в операции сложения + из-за
строгой типизации объектов в Python. Автоматическое преобразование типов не
производится в Python.


# 3.

In [8]:
dict1 = {'one': 1}
dict1['one'] = 11 # изменение значения с использованием индексации
dict1['one'] # извлечение значения с использованием индексации
dict1['new'] = 2
dict1
dict1[1,2] = 12
dict1

{'one': 11, 'new': 2, (1, 2): 12}

In [10]:
dict1['two']

KeyError: 'two'

Тут ошибка возникает из за того что индексация по несуществующему ключу словаря приводит к ошибке.

# 4.

In [14]:
t = [1,2], {1:2}, {1,2}; t[0] = 0

TypeError: 'tuple' object does not support item assignment

Ошибка возникает потому, что мы пытаемся изменить значение элемента кортежа. В Python, кортежи являются неизменяемыми (immutable) структурами данных, что означает, что их элементы нельзя изменять после создания.

# 5.

In [18]:
{1, 'str', (1,)}.add([1])


TypeError: unhashable type: 'list'

ошибка возникает так как элементами множества могут являться только объекты неизменяемых типов: число,
строка, кортеж. а мы пытаемся добавить список , который является изменяемым типом.


# 6.

In [24]:
dict1 = dict(one=1, two=2)
dict1.keys(), dict1.values(), dict1.items()



(dict_keys(['one', 'two']),
 dict_values([1, 2]),
 dict_items([('one', 1), ('two', 2)]))

In [26]:
print(dict1.get('one'), dict1.get('three'))
dict1['three']

1 None


KeyError: 'three'

Ошибка возникает так как ,мы пытаемся получить доступ к ключу `'three'`, которого нет в словаре dict1. Когда мы пишем `dict1['three']`, Python пытается найти значение для ключа `'three'`, но не может его найти, так как этого ключа не существует в словаре. 

# 7.

In [32]:
s = '+'.join('string'); s

print(s, s.find('-'))
s.index('-')


s+t+r+i+n+g -1


ValueError: substring not found

подстрока не содержится в строке поэтому `python` выдает ошибку

# 8.

In [36]:
a = 1 # создание переменной
a, d


NameError: name 'd' is not defined

Чтобы переменную можно было использовать, ей обязательно должно быть
присвоено значение. Использование переменной до того, как ей было присвоено
значение, всегда приведет к ошибке.

# 9.

In [40]:
print(abs(-1))
abs = 5
print(abs(-1))


1


TypeError: 'int' object is not callable

Ошибка возникает из-за того, что мы переопределяем встроенную функцию `abs` в `Python`, присваивая ей значение `5`. После этого `abs` больше не ссылается на встроенную функцию, которая вычисляет абсолютное значение числа. Вместо этого она становится обычной переменной с целочисленным значением `5`.

# Задание 3.

# Глава 4. Вопрос 6.
# `Что такое “полиморфизм” и почему о нем нужно заботиться?`

“Полиморфизм” означает, что смысл операции (вроде +) зависит от объектов,
на которых она выполняется. Выясняется, что это (вероятно) ключевая идея правильного использования Python — отказ от ограничения кода конкретными типами делает этот код применимым ко многим типам

Примеры:   

In [47]:
print(len("Hello"))    
print(len([1, 2, 3]))  
print(len((4, 5, 6)))  
print(len({"a": 1, "b": 2}))

5
3
3
2


# Глава 5. Вопрос 1.
# `Каким будет значение выражения 2 * (3 + 4) в Python?`

Значением выражения будет 14, результат 2*7, поскольку круглые скобки приводят к выполнению сложения раньше умножения.

Еще несколько примеров:

In [52]:
2 * 3 + 4

10

результат 10 так как скобок нет, поэтому сначала идет умножение `2 на 3 равно 6` и потом `6 + 4 = 10`

# Глава 6. Вопрос 1.
# `Взгляните на следующие три оператора. Изменяют ли они значение, выводимое для А?`
`А = "spam”
В - А
В = "shrubbery"`


In [56]:
A = "spam"
B = A
B = "shrubbery"


In [60]:
print(A)

spam


как мы видим, для `A` по прежнему выводится `spam` так как: 
- В первой строке переменной `A` присваивается значение строки `"spam"`.

- Во второй строке переменной `B` присваивается значение переменной A, то есть `"spam"`.

- В третьей строке переменной `B` присваивается новое значение строки `"shrubbery"`, изменяя ее значение.

Таким образом, значение переменной `A` остается неизменным и равно `"spam"`, так как присваивание переменной `B` нового значения не влияет на переменную `A`.

# Глава 7. Вопрос 4.
# `Как бы вы могли изменить строку в Python?`

Строки не могут быть модифицированы; они неизменяемы. Однако похожего
результата можно добиться путем создания новой строки — за счет конкатенации, нарезания, выполнения выражений форматирования либо использования
вызова метода, подобного replace, — и затем присваивания результата исходной переменной.

`ПРИМЕРЫ:`

In [72]:
origin = "Hello"
print(origin)
new = origin + " MIR"
print(new)  


Hello
Hello MIR


In [74]:
origin = "Hello, 123!"
print(origin)
new = origin.replace("123", "MIR")
print(new)  


Hello, 123!
Hello, MIR!


# Глава 8. Вопрос 3.
# ` Назовите четыре операции, которые изменяют списковый объект на месте. `

# 1. `append():`

In [8]:
list = [1, 2, 3]
list.append(4)
print(list)  


[1, 2, 3, 4]


# 2.`pop`

In [11]:
list.pop(2)
print(list)  


[1, 2, 4]


# 3. `reverse()`

In [14]:
list.reverse()
print(list)

[4, 2, 1]


# 4. `remove()` (удаление первого вхождения элемента)

In [20]:
list2 = [1,2,3,4,3,5,3]
list2.remove(3)
print(list2)

[1, 2, 4, 3, 5, 3]


# Глава 9. Вопрос 7.
# `В чем заключается ваша цель?`

Можно много написать про мою цель и написать бонально изучение Python, но основная цель всеже как можно больше набить руку и саморазвиться в этом.